import { StyleSheet } from 'react-native';

export const ForgotColors = {
  bg: '#0F0F14',
  card: '#1A1A22',
  border: '#2A2A36',
  textPrimary: '#F6F7FB',
  textSecondary: '#A2A5B3',
  accent: '#D8B4FE',
  accentDisabled: '#5A4A73',
  inputBg: '#171720',
  error: '#FF6B6B',
};

export const forgotStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: ForgotColors.bg,
    paddingHorizontal: 20,
  },
  backWrap: {
    marginTop: 8,
    marginBottom: 18,
    alignSelf: 'flex-start',
    paddingVertical: 4,
  },
  card: {
    backgroundColor: ForgotColors.card,
    borderColor: ForgotColors.border,
    borderWidth: 1,
    borderRadius: 20,
    padding: 20,
    gap: 14,
  },
  iconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#13131A',
    borderWidth: 1,
    borderColor: ForgotColors.border,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 8,
  },
  title: {
    color: ForgotColors.textPrimary,
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
  },
  subtitle: {
    color: ForgotColors.textSecondary,
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 4,
  },
  label: {
    color: ForgotColors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 6,
  },
  input: {
    backgroundColor: ForgotColors.inputBg,
    borderColor: ForgotColors.border,
    borderWidth: 1,
    borderRadius: 12,
    color: ForgotColors.textPrimary,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  inputError: {
    borderColor: ForgotColors.error,
  },
  errorText: {
    color: ForgotColors.error,
    fontSize: 12,
    marginTop: 6,
  },
  actionBtn: {
    marginTop: 8,
    backgroundColor: ForgotColors.accent,
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: 'center',
    minHeight: 48,
    justifyContent: 'center',
  },
  actionBtnPressed: {
    opacity: 0.85,
  },
  actionBtnDisabled: {
    backgroundColor: ForgotColors.accentDisabled,
  },
  actionText: {
    color: '#14121A',
    fontSize: 16,
    fontWeight: '700',
  },
  helperText: {
    color: ForgotColors.textSecondary,
    fontSize: 13,
    textAlign: 'center',
  },
  linkText: {
    color: ForgotColors.accent,
    fontWeight: '700',
  },
  codeInput: {
    letterSpacing: 5,
    textAlign: 'center',
    fontWeight: '700',
    fontSize: 16,
  },
  topDivider: {
    marginHorizontal: -20,
    borderBottomWidth: 1,
    borderBottomColor: ForgotColors.border,
    marginBottom: 20,
  },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  backText: {
    color: '#11E0E8',
    fontSize: 16,
    fontWeight: '600',
  },
  inboxCard: {
    backgroundColor: ForgotColors.card,
    borderColor: ForgotColors.border,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 22,
    alignItems: 'center',
    gap: 12,
  },
  mailSpriteWrap: {
    width: 96,
    height: 96,
    borderRadius: 20,
    backgroundColor: '#12331F',
    borderWidth: 1,
    borderColor: '#1F7E38',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  inboxTitle: {
    color: ForgotColors.textPrimary,
    fontSize: 34,
    fontWeight: '700',
    marginBottom: 6,
    textAlign: 'center',
  },
  inboxSubtitle: {
    color: ForgotColors.textSecondary,
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 14,
  },
  inboxEmailText: {
    color: ForgotColors.textPrimary,
    fontWeight: '700',
  },
  timerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#3B3211',
    borderWidth: 1,
    borderColor: '#8D7A2B',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginBottom: 14,
  },
  timerText: {
    color: '#FFE066',
    fontSize: 14,
    fontWeight: '700',
  },
  stepsWrap: {
    width: '100%',
    gap: 10,
    marginBottom: 14,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  stepText: {
    color: ForgotColors.textSecondary,
    fontSize: 15,
    flex: 1,
    lineHeight: 21,
  },
  resendWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  resendLead: {
    color: ForgotColors.textSecondary,
    fontSize: 14,
  },
  resendAction: {
    color: '#11E0E8',
    fontSize: 14,
    fontWeight: '700',
  },
  emailButton: {
    width: '100%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#3B3B4E',
    backgroundColor: '#242435',
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  emailButtonText: {
    color: ForgotColors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  pass3Card: {
    backgroundColor: ForgotColors.card,
    borderColor: ForgotColors.border,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 12,
  },
  pass3Title: {
    color: ForgotColors.textPrimary,
    fontSize: 34,
    textAlign: 'center',
    fontWeight: '700',
  },
  pass3Subtitle: {
    color: ForgotColors.textSecondary,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    marginBottom: 6,
  },
  pass3Badge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#173620',
    borderColor: '#2A7A41',
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  pass3BadgeText: {
    color: '#57F65A',
    fontSize: 14,
    fontWeight: '600',
  },
  passInputWrap: {
    marginTop: 4,
  },
  passInputShell: {
    backgroundColor: ForgotColors.inputBg,
    borderColor: ForgotColors.border,
    borderWidth: 1,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 54,
    paddingHorizontal: 14,
    gap: 10,
  },
  passInputField: {
    flex: 1,
    color: ForgotColors.textPrimary,
    fontSize: 16,
  },
  eyeAction: {
    color: '#8C90A3',
    fontWeight: '600',
    fontSize: 14,
  },
  strengthRow: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 10,
  },
  strengthBar: {
    flex: 1,
    height: 4,
    borderRadius: 999,
    backgroundColor: '#313347',
  },
  strengthBarActive: {
    backgroundColor: '#57F65A',
  },
  strengthLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
    marginBottom: 6,
  },
  strengthLabelText: {
    color: '#8C90A3',
    fontSize: 11,
  },
  reqList: {
    gap: 6,
    marginTop: 4,
    marginBottom: 4,
  },
  reqRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  reqText: {
    color: ForgotColors.textSecondary,
    fontSize: 14,
  },
  reqTextPass: {
    color: '#57F65A',
  },
  pass3Cta: {
    marginTop: 10,
    backgroundColor: '#C9CBD8',
    borderRadius: 14,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pass3CtaEnabled: {
    backgroundColor: ForgotColors.accent,
  },
  pass3CtaText: {
    color: '#20222E',
    fontSize: 16,
    fontWeight: '700',
  },
});
